### ISSUE TITLE
IDM221 Final Feedback

### ISSUE THREAD

**Issue by philsinatra** [bschenerman/idm221#1]
Overall there's good potential. I think if you focus hard from the beginning of the project next term you could build something really solid and interesting.

## Issues

1. There are no `alt` attributes on your images. [View the error report](https://validator.w3.org/nu/?doc=http%3A%2F%2Fbenschenerman.com%2Fportfolio.html).
1. Contact page also contains multiple HTML errors. [View the error report](https://validator.w3.org/nu/?doc=http%3A%2F%2Fbenschenerman.com%2Fcontact.html)
1. Your _portfolio_ page structure looks good, but you're missing some critical CSS for calculating the height of your parent containers that contain floating elements. If you inspect `.content_slab` and `.row` you will find their calculated `height` values are 0. Parent elements whose children are floating should include `overflow:auto;` as a fix for this 🐛 bug.
![screen shot 2017-12-15 at 9 37 08 am](https://user-images.githubusercontent.com/1465808/34046654-cee2455e-e17b-11e7-8678-1647b71fa082.png)
![screen shot 2017-12-15 at 9 36 54 am](https://user-images.githubusercontent.com/1465808/34046671-d84d9544-e17b-11e7-9d61-9bb8b378d732.png)
1. Your project pages could benefit from some design adjustments, specifically a consistent width for the content. A single container that houses all of the content would help create a more polished, consistent look across all of the pages.
![ben schenerman](https://user-images.githubusercontent.com/1465808/34046767-1fafa972-e17c-11e7-93a9-6bd5b162e0b5.png)

**Comment by bschenerman** [comment]
1. If you check the element inspector or the js you'll see the alt text. It was late and it felt silly to update 20+ imgs in HTML so i did it in 2 lines of code instead.

2. True. 

3. Ahhhhh thank you this was driving me insane because I wanted to set bottom margins for the page. I was sure we had gone over it in class but I took the hit on it because it was late. 

4. There are containers on everything. Did you view this on a wide screen? Most likely what happened is I forgot to set max-width because I was working on a laptop, so the paragraph expanded while the rest of the content did not due to it's natural size. You're still right that I should've accounted for it but I want to specify that I used a 12 col grid for designing this page which is why not everything should fit cleanly down one column.

**Comment by philsinatra** [comment]
> 1. If you check the element inspector or the js you'll see the alt text. It was late and it felt silly to update 20+ imgs in HTML so i did it in 2 lines of code instead.

There are two problems with this approach. 

1. Valid HTML requires the `alt` attribute to be programmed in the HTML. Your method fails error testing and does not work for any user with JavaScript disabled.
1. "Project Preview Number 2" is not a good `alt` attribute. The point of the attribute is to provide a text description of what is being shown in the image for users who can't see the image.

> 4. There are containers on everything. Did you view this on a wide screen? Most likely what happened is I forgot to set max-width because I was working on a laptop, so the paragraph expanded while the rest of the content did not due to it's natural size. You're still right that I should've accounted for it but I want to specify that I used a 12 col grid for designing this page which is why not everything should fit cleanly down one column.

I mostly meant it would be nice if all the containers had the same width so the layout appeared more uniform.

**Comment by bschenerman** [comment]
1. Ah. Good point. [About 1-2% of users disable js](http://www.punkchip.com/why-support-javascript-disabled/) in 2014 but I'll keep that in mind for degradation purposes. I suppose if I want to do that programmatically in the future it should be server side. It's not a great alt attribute but it's at least partially descriptive. Granted, I don't think I'd ever put that in actual production code so I'll take the hit on this one. What I'm thinking for the future of this is to implement global content variables on the server that I can pull in along these lines:

```html
<img src=<php project[0].imgSrc ?> alt=<php project[0].title ?>>
```

4. Hmmm it sounds like you are saying that you're expecting it to all fit down a single width. From a design perspective, I think it would feel strange having paragraphs bounded by the image width, but it doesn't look fantastic as is. I'll spend some more time looking at precedent works and redesigning this page over break.
